### PR TITLE
Port to Python 3.5+ using six

### LINKED ISSUE #137: Add Python 3 compatibility
Are there any plans for updating bok-choy to be Python 3 compatible?

Python 3 is finally seeing major adoption... and I think the following Python versions should be targeted: 2.7, 3.3, 3.4, 3.5

Rather than creating a Python3 fork and maintaining 2 code bases, this would be best done by using a single code base that runs under Python 2 or Python 3.  (perhaps using `six` as a compatibility helper).

If there are no plans for this on the horizon, would a PR contributing Python3 support be considered for merging? (I might have spare cycles to take this on)

### PR DESCRIPTION
**Pull request by dstufft**
Fixes #137

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @dstufft! I've created [OSPR-1233](https://openedx.atlassian.net/browse/OSPR-1233) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf)     or indicated your institutional affiliation.     If you like, you can add yourself to the [AUTHORS](https://github.com/edx/bok-choy/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by dstufft** [comment]
I can't reproduce the test failures on Python 3.x locally (to be honest, running those tests just deadlocks for me locally).

**Comment by nedbat** [comment]
@dstufft Thanks so much! Keep us posted on the progress with the contributor agreement.  I understand HPE might be difficult...

**Comment by benpatterson** [comment]
Hi @dstufft thanks a lot for this work. I personally won't be able to look for a couple of days, but would be happy to if that would help.

CC @jzoldak

**Comment by benpatterson** [comment]
Hi @dstufft I looked at this today, and think it's [this expectedFailure regression in py 3.5.0](http://bugs.python.org/issue21112). Travis [doesn't appear to have](https://docs.travis-ci.com/user/languages/python#On-demand-installations) 3.5.1 and above, just 3.5.0 and 3.5-dev.

Because these have been expected failures for a long time, we can consider skipping them instead.

**Comment by jzoldak** [comment]
@dstufft @benpatterson FWIW in another project that I happen to be working on that has nothing to do with this one, I had [set the python version to 3.5.1 in the travis.yaml](https://github.com/Bernie-2016/Connect-SharkWeek/blob/master/.travis.yml#L4) and travis [downloaded and installed that version successfully](https://travis-ci.org/Bernie-2016/Connect-SharkWeek/builds/124002419). So you might want to try out 3.5.1 after all.

**Comment by nedbat** [comment]
@dstufft Are you working on the contributor agreement, or should we get this ported another way?

**Comment by dstufft** [comment]
Let me poke my manager again to see what the status of that is.

**Comment by jzoldak** [comment]
@dstufft I'm looking to show bok-choy some love and had Python 3 compatibility on my list. Any update on whether we'll be able to merge your PR into the codebase?

**Comment by dstufft** [comment]
Sorry, we had some internal rearrangements and my manager switched in the process of that and I sort of forgot about this. I asked my new manager about it and she's going to figure it out.

**Comment by dstufft** [comment]
To be clear, if you want to recreate this work and just make your own PR I'm not going to feel bad about it. The changes were largely mechanical in nature either way.

**Comment by jzoldak** [comment]
@dstufft During a hackathon here at edX yesterday and today an impromptu team here was able to bust out a number of improvements that we've been wanting to make with bok-choy, including redoing the python 3 upgrade work. 

Thanks again so much for your inspiration/encouragement to get this done.

Not sure if we'll be able to close the loop on publishing to PyPI today as we're heading into demos in a few minutes. But if not today then early next week for sure.

**Comment by jzoldak** [comment]
Implemented in #168

**Comment by dstufft** [comment]
Sounds good, thanks a lot!

**Comment by jzoldak** [comment]
@dstufft sorry, forgot to publish the changes. 
Python 3 support is now available in [version 0.6.0 up on PyPI](https://pypi.python.org/pypi/bok_choy/0.6.0).

**Pull request closed without merging**
