### PR TITLE
Adds impact to the error output

### PR DESCRIPTION
**Pull request by clrux**
I recently added a few [new checks to our custom ruleset](https://github.com/edx/edx-custom-a11y-rules/pull/3) listed as "minor" severity. While the failures will cause Jenkins to fail, it will indicate to developers and PR reviewers that the failures, if "minor" severity, can be skipped at this time.

This work relates to [this comment](https://github.com/edx/edx-custom-a11y-rules/pull/3#discussion_r65388499).

> Ok, I hear you. I think you are addressing the point of failing or not-failing, which makes sense. But I guess I'm wondering, how would a developer know if the issue is minor or critical when running tests? Is there any hint to give that indication (other than the fail or pass overall)?

## Reviewer

- [x] @benpatterson

### CODE REVIEW

**Comment by benpatterson** [comment]
@clrux would you mind posting an example of how this will look to a developer reviewing test results?

**Comment by clrux** [comment]
@benpatterson It would look like this:

```
Severity: minor
Rule ID: link-href
Help URL: https://openedx.atlassian.net/wiki/display/A11Y/edX+Specific+Accessibility+Tests

	Message: href value MUST NOT be empty or "#"
	Html: <a class="active-section" href="" data-section="course_info">Course Info</a>
	Target: [u'#instructor-dashboard-content > .instructor-nav > li:nth-of-type(1) > .active-section']
```

**Comment by clrux** [comment]
I chose to put the severity first so issues can be scanned fairly easily based on priority.

**Comment by benpatterson** [comment]
:+1:

**Pull request merged**
