### PR TITLE
#201 Allow extra desired capabilities

### PR DESCRIPTION
**Pull request by goodspark**
If this approach looks good to you all, I'll also push a commit to add some docs.

Ref: https://github.com/edx/bok-choy/issues/201

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @goodspark! I've created [OSPR-2283](https://openedx.atlassian.net/browse/OSPR-2283) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf)     or indicated your institutional affiliation.     If you like, you can add yourself to the [AUTHORS](https://github.com/edx/bok-choy/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by goodspark** [comment]
Looks like the py35 failure is unrelated. Most likely a timeout trying to load the Github page.
https://travis-ci.org/edx/bok-choy/jobs/350729375#L712

**Comment by nedbat** [comment]
@goodspark Thanks for the contribution! Let me know when you've sent in the contributor agreement.

**Comment by goodspark** [comment]
Working on it with our legal team!

**Comment by goodspark** [comment]
@nedbat FYI good to go on the contributor agreement!

**Comment by nedbat** [comment]
@goodspark Thanks, we have the agreement.

**Comment by nedbat** [comment]
@michaelyoungstrom Would this be for you? Or recommend someone else? Thanks.

**Comment by estute** [comment]
@goodspark this seems reasonable. The only thing I would consider is potential for drift between how tests should be invoked or configured, depending on whether or not the browser is local or remote. For instance, you would need to use environment variables to set capabilities when testing locally, but would use your feature when testing in a grid (as not all of the desired capabilities are specific to remote browsers).

**Comment by goodspark** [comment]
@estute True, but I think coding in 1st class support for every testing service is not a scalable approach. If I didn't need to worry about backwards compatibility, I would simply remove all the env var-based configuration and ask users to pass desired capabilities directly. For people used to writing UI code without a framework and just selenium, this is the most familiar and searching online for solutions related to browser setup usually involves adjusting the desired capabilities.

But as is, if users do not want specific browser configs, they can use the existing env-var based config for both local and remote browser runs.

The drift can definitely happen over time. I think bok-choy would then need to pick one approach and stick to it. I'm in favor of this method, as it means less maintenance on this repo for new/changed services, more common setup for users moving across frameworks, slightly less code in this repo.

Thoughts?

**Comment by mduboseedx** [comment]
@estute @goodspark Where are we with this discussion?

**Comment by goodspark** [comment]
The question remains whether exposing the general capabilities dictionary is the suited approach for bok-choy.

**Comment by natabene** [comment]
@goodspark  Looks like one test is still failing. Do you think you need to rebase, as time has passed since this PR has been opened?

**Comment by goodspark** [comment]
@natabene https://travis-ci.org/edx/bok-choy/jobs/350729375#L534

Given this PR hasn't touched any dependency files, I'm inclined to think this is a general build problem or flakiness with Travis.

**Comment by goodspark** [comment]
Done!

**Comment by natabene** [comment]
@estute Do you want to take another look or is this good to move to platform team for review?

**Comment by estute** [comment]
@natabene I think this is good to go. Merging. @goodspark thanks for taking care of this.

**Comment by edx-webhook** [comment]
@goodspark 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/bok-choy&entry.867055334=https://github.com/edx/bok-choy/pull/202&entry.1484655318=https://github.com/goodspark&entry.752974735=2018-03-08+08:55&entry.1917517419=2018-11-13+15:36&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
