### PR TITLE
Add ability to save browser page source to disk

### PR DESCRIPTION
**Pull request by jzoldak**
@cgoldberg @mlkwaqas

### CODE REVIEW

**Comment by jzoldak** [comment]
I think all that is left for #86 is to save the page source on failure.

**Comment by dianakhuang** [comment]
@jzoldak @benpatterson Could you review this PR? I believe I handled the merge conflicts correctly, but I'd like some more eyes on it.

Also, the test failure is related to HAR capture, which is a feature we're removing anyway.

**Comment by dianakhuang** [comment]
@jmbowman @ajpal @thallada

**Comment by dianakhuang** [comment]
We've got a clean build, hooray!

**Comment by jzoldak** [comment]
👍

**Pull request merged**
