### PR TITLE
Add coveralls to travis builds.

### PR DESCRIPTION
**Pull request by benpatterson**

### CODE REVIEW

**Comment by benpatterson** [comment]
@jzoldak @clytwynec :)

**Comment by clytwynec** [comment]
:+1: awesome!

**Comment by jzoldak** [comment]
@benpatterson This will start tracking coverage, and we can add a badge to the readme at a later time?
:+1:

**Comment by benpatterson** [comment]
@jzoldak It stores coverage, but I'm not sure how long coveralls keeps the data. ...And yes, we can add a badge once this is on master.

**Pull request merged**
