### PR TITLE
Update reference. We use slack now not IRC.

### PR DESCRIPTION
**Pull request by jzoldak**
@benpatterson or @jbarciauskas

### CODE REVIEW

**Comment by nedbat** [comment]
ugh, we should really have this info in one central place, and just point to it from each repo instead of having to tweak them all when we change our minds next time.

**Comment by jzoldak** [comment]
@nedbat I totally agree. Not sure how to do that tho? Do you know where a good place to put that would be and how to pull in the info?

**Comment by benpatterson** [comment]
I see the discussion....how about a wiki page?

**Comment by jzoldak** [comment]
Oh, hm, maybe we just point them to https://open.edx.org/ ?

**Comment by nedbat** [comment]
@jzoldak btw, I didn't mean to hold this up from getting merged.  It's good to fix the references we have.

**Comment by benpatterson** [comment]
Yeah this is a :+1: from me. The centralized-info change could come later.

**Comment by jzoldak** [comment]
Ok cool, merging this now. We'll figure out the other stuff later.

**Pull request merged**
